# Generated by Django 4.0.3 on 2022-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
